vich_uploader:
    db_driver: orm

    mappings:
       products:
           uri_prefix: /images/products
           upload_destination: '%kernel.project_dir%/public/img/products' #dossier ou il va sauvegarder les images
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
